# Generated by Django 4.2.1 on 2023-06-14 01:21

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_message_delete_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto'),
        ),
    ]
