# Generated by Django 4.2.1 on 2023-06-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message_delete_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
