# Generated by Django 4.2.1 on 2023-06-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_message_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='respons_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
