# Generated by Django 4.2.1 on 2023-05-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('done', models.CharField(choices=[('doing', 'Aberto'), ('done', 'Concluido')], max_length=7)),
                ('created_task', models.DateTimeField(auto_now_add=True)),
                ('updated_task', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
