# Generated by Django 4.2.1 on 2023-05-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_datatime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dataTime',
            new_name='EndTime',
        ),
    ]
