# Generated by Django 4.2.1 on 2023-06-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
