# Generated by Django 4.2.1 on 2023-06-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Escala',
            field=models.CharField(blank=True, choices=[('a', 'A1'), ('b', 'B2'), ('c', 'C3'), ('d', 'D4'), ('e', 'E5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'Aberto'), ('done', 'Concluido'), ('fail', 'Falha')], max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
