# Generated by Django 4.2.1 on 2023-06-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_escala_alter_task_done_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Escala',
            field=models.CharField(choices=[('all', 'Todas'), ('a', 'A1'), ('b', 'B2'), ('c', 'C3'), ('d', 'D4'), ('e', 'E5')], default='all', max_length=10),
        ),
    ]
