# Generated by Django 4.2.1 on 2023-06-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Escala',
            field=models.CharField(blank=True, choices=[('all', 'Todas'), ('a', 'A1'), ('b', 'B2'), ('c', 'C3'), ('d', 'D4'), ('e', 'E5')], max_length=10, null=True),
        ),
    ]
