# Generated by Django 4.2.1 on 2023-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_task_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'Aberto'), ('done', 'Concluido'), ('fail', 'Falha')], default='doing', max_length=7),
        ),
    ]
